# Environment variables take precedence over this file

grafana:
  # Grafana instance URL (required)
  host: "your-host"

  api_key: "your-api-key"
  ssl_verify: "true"

server:
  # Port to run the MCP server on
  port: 8000

  # Debug mode
  debug: true
