# Environment variables take precedence over this file

grafana:
  # Grafana instance URL (required)
  host: <host>

  api_key: <api_key>
  ssl_verify: <ssl_verify>

server:
  # Port to run the MCP server on
  port: 8000

  # Debug mode
  debug: true
